/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AApp {
    }
    interface ARoute {
    }
    interface ARouter {
    }
}
declare global {
    interface HTMLAAppElement extends Components.AApp, HTMLStencilElement {
    }
    var HTMLAAppElement: {
        prototype: HTMLAAppElement;
        new (): HTMLAAppElement;
    };
    interface HTMLARouteElement extends Components.ARoute, HTMLStencilElement {
    }
    var HTMLARouteElement: {
        prototype: HTMLARouteElement;
        new (): HTMLARouteElement;
    };
    interface HTMLARouterElement extends Components.ARouter, HTMLStencilElement {
    }
    var HTMLARouterElement: {
        prototype: HTMLARouterElement;
        new (): HTMLARouterElement;
    };
    interface HTMLElementTagNameMap {
        "a-app": HTMLAAppElement;
        "a-route": HTMLARouteElement;
        "a-router": HTMLARouterElement;
    }
}
declare namespace LocalJSX {
    interface AApp {
    }
    interface ARoute {
    }
    interface ARouter {
    }
    interface IntrinsicElements {
        "a-app": AApp;
        "a-route": ARoute;
        "a-router": ARouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-app": LocalJSX.AApp & JSXBase.HTMLAttributes<HTMLAAppElement>;
            "a-route": LocalJSX.ARoute & JSXBase.HTMLAttributes<HTMLARouteElement>;
            "a-router": LocalJSX.ARouter & JSXBase.HTMLAttributes<HTMLARouterElement>;
        }
    }
}
