/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AApp {
    }
    interface ALink {
        "href": string;
    }
    interface ARouter {
    }
}
declare global {
    interface HTMLAAppElement extends Components.AApp, HTMLStencilElement {
    }
    var HTMLAAppElement: {
        prototype: HTMLAAppElement;
        new (): HTMLAAppElement;
    };
    interface HTMLALinkElement extends Components.ALink, HTMLStencilElement {
    }
    var HTMLALinkElement: {
        prototype: HTMLALinkElement;
        new (): HTMLALinkElement;
    };
    interface HTMLARouterElement extends Components.ARouter, HTMLStencilElement {
    }
    var HTMLARouterElement: {
        prototype: HTMLARouterElement;
        new (): HTMLARouterElement;
    };
    interface HTMLElementTagNameMap {
        "a-app": HTMLAAppElement;
        "a-link": HTMLALinkElement;
        "a-router": HTMLARouterElement;
    }
}
declare namespace LocalJSX {
    interface AApp {
    }
    interface ALink {
        "href"?: string;
        "onRedirected"?: (event: CustomEvent<any>) => void;
    }
    interface ARouter {
    }
    interface IntrinsicElements {
        "a-app": AApp;
        "a-link": ALink;
        "a-router": ARouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "a-app": LocalJSX.AApp & JSXBase.HTMLAttributes<HTMLAAppElement>;
            "a-link": LocalJSX.ALink & JSXBase.HTMLAttributes<HTMLALinkElement>;
            "a-router": LocalJSX.ARouter & JSXBase.HTMLAttributes<HTMLARouterElement>;
        }
    }
}
